# Generated by Django 4.2.7 on 2025-07-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='onsite_address',
            field=models.CharField(blank=True, help_text='Address for onsite sessions', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_type',
            field=models.CharField(choices=[('video_call', 'Video Call'), ('audio_call', 'Audio Call'), ('chat', 'Chat'), ('onsite', 'Onsite')], default='video_call', max_length=20),
        ),
    ]
