# Generated by Django 4.2.7 on 2025-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_onsite_address_alter_booking_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='onsite_address',
            field=models.CharField(blank=True, help_text='Address for onsite sessions', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_type',
            field=models.CharField(choices=[('video_call', 'Video Call'), ('audio_call', 'Audio Call'), ('chat', 'Chat'), ('in_person', 'In Person')], default='video_call', max_length=20),
        ),
    ]
